### ISSUE TITLE
City icon size consistency

### ISSUE THREAD

**Issue by yohanboniface** [tilery/pianoforte#27]
Seems to me the size of the icons of the city could be more consistent:

Filled circle vs stroked circle; circle vs square…

Maybe we could have a little help from the designers here?

![screenshot-20180219210929-2434x1644](https://user-images.githubusercontent.com/146023/36395415-5e3f9d34-15b9-11e8-941a-3e64d2f4baf8.png)

**Comment by yohanboniface** [comment]
Having a new look at this, I even feel like there is too much icons.
At the moment, we have:
![screenshot-20180301151610-354x467](https://user-images.githubusercontent.com/146023/36849137-8368f036-1d63-11e8-911a-bca5509c899b.png)

Which is a cumulative of city size AND French presence. I think we should combine them instead, having for example:
- three shape depending of the city size (eg. round, square, star for town, city, capital)
- filled shape or not depending of the French presence or not

@kent1D  Thoughts? Could we have the designers to work on this?

**Comment by kent1D** [comment]
You mean better if we have : 

* black filled stars : cities with embassies 
* transparent stars : capital cities

* black filled square : cities with other french presence (consulates)
* transparent squares : other cities from OSM

* black filled round (or transparent, if we really want to be coherent) :  for other cities

is it?

Because it's moreover what we have, just a switch entre deux

**Comment by yohanboniface** [comment]
Yes, with shape more homogeneous :)

**Comment by kent1D** [comment]
Ok perfect for me

**Comment by kent1D** [comment]
I will ask them, but won’t have anything before next week. One of them is on holidays

**Comment by kent1D** [comment]
Fixed by #43
